name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis/redis-stack-server
        ports:
          - "6379:6379"
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.
    env:
      REDIS_HOST: localhost
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun nx run-many -t test
      - run: bun scripts/version.ts
      - run: bun nx run-many -t publish
